apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
    # By using readOnly, this container will just read the logs and push.
  - image: almalinux:9
    name: almalinux
    command: ["sleep", "2000"]
    volumeMounts:
    - mountPath: /mnt/nginx-logs
      name: nginx-logs
      readOnly: true
  # This is at the Pod level
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi