apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-demo
spec:
  containers:
  - name: nginx
    image: nginx
    # envFrom is used in a Pod spec to load all key–value pairs from a ConfigMap or Secret as environment variables into a container.
    envFrom:
    - configMapRef:
        name: nginx-config