# Service is an object that provides a stable network endpoint to access a group of Pods.
# A service is a method for exposing a network application that is running on one or more Pods in your cluster.
# By default, it will be acting as cluster ip.
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Container Port    