# Service is an object that provides a stable network endpoint to access a group of Pods.
# A service is a method for exposing a network application that is running on one or more Pods in your cluster.
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    # Labels are used as selectors.
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80            # Service Port
    targetPort: 80      # Container Port 
    nodePort: 32141     # We can specify from 30000-32767 ephemeral nodeport range so as not to change the sg all the time whenever new nodeport is created.