# This is for Headless Service
# Create multiple replicas of your pod. Always runs desired number of pods.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # These labels are replicaset labels reference
  labels:
    project: roboshop
    purpose: replicaset-demo
    tier: frontend
    component: frontend
  annotations:
    kubernetes.io/change-cause: "Moving to 1.29.7"    # It will be used in 'kubectl rollout history'
spec:
  replicas: 4
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      purpose: replicaset-demo
      tier: frontend
      component: frontend
  # This is Pod definition, Pod is subset of replicaset
  template:
    metadata:
      # These MUST match the 'selector' labels specified above
      labels:
        project: roboshop
        purpose: replicaset-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.7
---
# A service is a method for exposing a network application that is running on one or more Pods in your cluster.
apiVersion: v1
kind: Service     # Used for Load Balancing
metadata:
  name: nginx
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Container Port    
---
# Headless Service --> A headless service is a service without a cluster IP.
apiVersion: v1
kind: Service     # It is used to find other nodes IP address in cluster for data replication
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    # Labels are used as selectors.
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Container Port 

# This is for Deployment
# # Create multiple replicas of your pod. Always runs desired number of pods. 
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   # These labels are replicaset labels reference
#   labels:
#     project: roboshop
#     purpose: rs-demo
#     tier: frontend
#     component: frontend
#   annotations:
#     kubernetes.io/change-cause: "Moving to 1.29.7"    # It will be used in 'kubectl rollout history'
# spec:
#   replicas: 2
#   selector:
#   # Using these labels, replicaset selects the pod.
#     matchLabels:
#       project: roboshop
#       purpose: rs-demo
#       tier: frontend
#       component: frontend
#   # This is Pod definition, Pod is subset of replicaset
#   template:
#     metadata:
#       # These MUST match the 'selector' labels specified above
#       labels:
#         project: roboshop
#         purpose: rs-demo
#         tier: frontend
#         component: frontend
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.29.7